// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Env.apiKeyWeb,
    appId: '1:497207540886:web:9ad66e4979a082ab8bd6b7',
    messagingSenderId: '497207540886',
    projectId: 'sakn-gdg-benha',
    authDomain: 'sakn-gdg-benha.firebaseapp.com',
    storageBucket: 'sakn-gdg-benha.firebasestorage.app',
    measurementId: 'G-R1ZJ3H9TPL',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.apiKeyAndroid,
    appId: '1:497207540886:android:0d50f0ef0f8614de8bd6b7',
    messagingSenderId: '497207540886',
    projectId: 'sakn-gdg-benha',
    storageBucket: 'sakn-gdg-benha.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.apiKeyIos,
    appId: '1:497207540886:ios:1d34c5f122f97bab8bd6b7',
    messagingSenderId: '497207540886',
    projectId: 'sakn-gdg-benha',
    storageBucket: 'sakn-gdg-benha.firebasestorage.app',
    iosBundleId: 'com.sakn.sakn',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.apiKeyMac,
    appId: '1:497207540886:ios:1d34c5f122f97bab8bd6b7',
    messagingSenderId: '497207540886',
    projectId: 'sakn-gdg-benha',
    storageBucket: 'sakn-gdg-benha.firebasestorage.app',
    iosBundleId: 'com.sakn.sakn',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: Env.apiKeyWindows,
    appId: '1:497207540886:web:95ef80ba418fe0318bd6b7',
    messagingSenderId: '497207540886',
    projectId: 'sakn-gdg-benha',
    authDomain: 'sakn-gdg-benha.firebaseapp.com',
    storageBucket: 'sakn-gdg-benha.firebasestorage.app',
    measurementId: 'G-MQMQPT4X03',
  );
}
